name: CI

on:
    pull_request:
        branches: [main]

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest

        steps:
          - name: Check out code
            uses: actions/checkout@v4
            
          - name: Setup Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.11'
                cache: 'pip'
                
          - name: Install dependiences
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest pytest-cov pytest-mock
          
          - name: Test with pytest
            run: |
                pytest --cov=app tests/

    pyre:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
    
            - name: Run Pyre Action
              uses: facebook/pyre-action@v0.0.2
              with:
                repo-directory: './'
                requirements-path: 'requirements.txt'