name: CI

on:
    pull_request:
        branches: [main]

jobs:
    lint-and-test:
        name: Test and Lint
        runs-on: ubuntu-latest

        steps:
          - name: Check out code
            uses: actions/checkout@v4
            
          - name: Setup Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.11'
                cache: 'pip'

          - name: Lint with flake8
            uses: py-actions/flake8@v2
                
          - name: Install dependiences
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest pytest-cov pytest-mock
          
          - name: Test with pytest
            run: |
                pytest --cov=app tests/
            